export const PRODUCTS = [
  {
    id: 1,
    name: "To Kill a Mockingbird",
    price: 10.99,
    rating: 4.8,
    fastDelivery: true,
    imageUrl: "https://covers.openlibrary.org/b/id/8226191-L.jpg",
    type: "Fiction",
    deliveryDays: 3,
  },
  {
    id: 2,
    name: "1984",
    price: 8.99,
    rating: 4.7,
    fastDelivery: true,
    imageUrl: "https://covers.openlibrary.org/b/id/8225634-L.jpg",
    type: "Dystopian",
    deliveryDays: 5,
  },
  {
    id: 3,
    name: "The Great Gatsby",
    price: 9.99,
    rating: 4.6,
    fastDelivery: true,
    imageUrl: "https://covers.openlibrary.org/b/id/7222246-L.jpg",
    type: "Classic",
    deliveryDays: 2,
  },
  {
    id: 4,
    name: "Pride and Prejudice",
    price: 7.99,
    rating: 4.5,
    fastDelivery: false,
    imageUrl: "https://covers.openlibrary.org/b/id/9251844-L.jpg",
    type: "Romance",
    deliveryDays: 7,
  },
  {
    id: 5,
    name: "The Catcher in the Rye",
    price: 11.99,
    rating: 4.3,
    fastDelivery: true,
    imageUrl: "https://covers.openlibrary.org/b/id/8225298-L.jpg",
    type: "Fiction",
    deliveryDays: 4,
  },
  {
    id: 6,
    name: "The Hobbit",
    price: 12.99,
    rating: 4.9,
    fastDelivery: false,
    imageUrl: "https://covers.openlibrary.org/b/id/6979862-L.jpg",
    type: "Fantasy",
    deliveryDays: 10,
  },
  {
    id: 7,
    name: "Jane Eyre",
    price: 10.49,
    rating: 4.7,
    fastDelivery: true,
    imageUrl: "https://covers.openlibrary.org/b/id/10525055-L.jpg",
    type: "Romance",
    deliveryDays: 3,
  },
  {
    id: 8,
    name: "Animal Farm",
    price: 6.99,
    rating: 4.4,
    fastDelivery: true,
    imageUrl: "https://covers.openlibrary.org/b/id/9619648-L.jpg",
    type: "Political",
    deliveryDays: 5,
  },
  {
    id: 9,
    name: "Moby Dick",
    price: 14.99,
    rating: 4.2,
    fastDelivery: false,
    imageUrl: "https://covers.openlibrary.org/b/id/7104438-L.jpg",
    type: "Adventure",
    deliveryDays: 8,
  },
  {
    id: 10,
    name: "War and Peace",
    price: 19.99,
    rating: 4.5,
    fastDelivery: false,
    imageUrl: "https://covers.openlibrary.org/b/id/8670565-L.jpg",
    type: "Historical",
    deliveryDays: 12,
  },
  {
    id: 11,
    name: "Brave New World",
    price: 8.49,
    rating: 4.6,
    fastDelivery: true,
    imageUrl: "https://covers.openlibrary.org/b/id/7222244-L.jpg",
    type: "Dystopian",
    deliveryDays: 6,
  },
  {
    id: 12,
    name: "The Alchemist",
    price: 9.99,
    rating: 4.8,
    fastDelivery: true,
    imageUrl: "https://covers.openlibrary.org/b/id/240727-L.jpg",
    type: "Adventure",
    deliveryDays: 4,
  },
  {
    id: 13,
    name: "Wuthering Heights",
    price: 10.99,
    rating: 4.3,
    fastDelivery: false,
    imageUrl: "https://covers.openlibrary.org/b/id/7798780-L.jpg",
    type: "Romance",
    deliveryDays: 9,
  },
  {
    id: 14,
    name: "The Book Thief",
    price: 11.49,
    rating: 4.8,
    fastDelivery: true,
    imageUrl: "https://covers.openlibrary.org/b/id/7266158-L.jpg",
    type: "Historical",
    deliveryDays: 3,
  },
  {
    id: 15,
    name: "The Lord of the Rings",
    price: 25.99,
    rating: 5.0,
    fastDelivery: false,
    imageUrl: "https://covers.openlibrary.org/b/id/8221920-L.jpg",
    type: "Fantasy",
    deliveryDays: 15,
  },
  {
    id: 16,
    name: "The Great Gatsby",
    price: 10.99,
    rating: 4.5,
    fastDelivery: true,
    imageUrl: "https://covers.openlibrary.org/b/id/7222246-L.jpg",
    type: "Classic",
    deliveryDays: 3,
  },
  {
    id: 17,
    name: "1984",
    price: 9.99,
    rating: 4.8,
    fastDelivery: false,
    imageUrl: "https://covers.openlibrary.org/b/id/8225634-L.jpg",
    type: "Dystopian",
    deliveryDays: 10,
  },
  {
    id: 18,
    name: "To Kill a Mockingbird",
    price: 8.99,
    rating: 4.9,
    fastDelivery: true,
    imageUrl: "https://covers.openlibrary.org/b/id/8226191-L.jpg",
    type: "Fiction",
    deliveryDays: 3,
  },
  {
    id: 19,
    name: "Pride and Prejudice",
    price: 7.99,
    rating: 4.7,
    fastDelivery: false,
    imageUrl: "https://covers.openlibrary.org/b/id/9251844-L.jpg",
    type: "Romance",
    deliveryDays: 7,
  },
  {
    id: 20,
    name: "The Catcher in the Rye",
    price: 6.99,
    rating: 4.2,
    fastDelivery: true,
    imageUrl: "https://covers.openlibrary.org/b/id/8225298-L.jpg",
    type: "Fiction",
    deliveryDays: 4,
  },
  {
    id: 21,
    name: "The Hobbit",
    price: 12.99,
    rating: 4.9,
    fastDelivery: false,
    imageUrl: "https://covers.openlibrary.org/b/id/6979862-L.jpg",
    type: "Fantasy",
    deliveryDays: 10,
  },
  {
    id: 22,
    name: "Moby-Dick",
    price: 11.49,
    rating: 4.3,
    fastDelivery: true,
    imageUrl: "https://covers.openlibrary.org/b/id/7104438-L.jpg",
    type: "Adventure",
    deliveryDays: 4,
  },
  {
    id: 23,
    name: "War and Peace",
    price: 14.99,
    rating: 4.6,
    fastDelivery: false,
    imageUrl: "https://covers.openlibrary.org/b/id/8670565-L.jpg",
    type: "Historical",
    deliveryDays: 12,
  },
];
